### ISSUE TITLE
() issue

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit/ashtadhyayi#2]
https://github.com/aupasana/ashtadhyayi/issues/10

There are many places where we see () in the text.
They are usually some replacement of conjoints.
They need to be examined and if possible, generically corrected.

**Comment by vvasuki** [comment]
मित्र @drdhaval2785 , http://ashtadhyayi.com/sutraani/1/1/56 इत्यादौ व्यर्थावरणानि नैव दृश्यन्ते। कामं @neeleshb अस्य श्रमः प्रयुज्यताम् पुनश्शोधनस्यापेक्षया।

**Comment by drdhaval2785** [comment]
It requires further examination.
I checked up. Currently in ashtadhyayi.com, the () are just hidden. Not
corrected.

**Comment by drdhaval2785** [comment]
![screenshot_20181223-013635_samsung internet](https://user-images.githubusercontent.com/5755132/50378257-f3921480-0653-11e9-8b13-2103dc66fe10.jpg)

**Comment by drdhaval2785** [comment]
Should be Tyu.

**Comment by neeleshb** [comment]
Yes I am just deleting / hiding "()".

**Comment by vvasuki** [comment]
A simpler fix to this might be to start off with the http://www.wilbourhall.org/sansknet/ version, pass it through the [tech hindi converter](https://github.com/sanskrit-coders/indic_transliteration/commit/a6c4489f74a364040baea8e21f252319a61bbd55) (suggesting fixes to anunad as you find errors).

As an example, for प्रत्यक्षानुमानशिष्ट्योर्ग्रहणमुपपद्यते, I observe that the converter currently yields a closer output - एवमुभयोः प्रत्यक्षानुमानशिष्ट्योग्ग्रहणमुपपद्यते (with just a wrong ग्):
rather than प्रत्यक्षानुमानशिष्ट()ओग्र्रहणमुपपद्यते (previous publicized version)

**Comment by vvasuki** [comment]
I am trying to get anunAd into github so that we can have more coherent conversations and be more productive.

**Comment by drdhaval2785** [comment]
Closing this issue.
I have completed regeneration of nyAsa from wilbourhall.

**Comment by vvasuki** [comment]
So almost no errors in nyAsa now?
