### ISSUE TITLE
Add padamanjari

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit/ashtadhyayi#7]
https://github.com/drdhaval2785/padamanjari/blob/master/padamanjari.txt  is the data sent by Prof. Ashok Aklujkar. It can be modified via some programmatic manner and used. 
Want to take it up @vvasuki ?

**Comment by vvasuki** [comment]
I recommend against processing that raw file and suggest that http://ashtadhyayi.com/sutraani/1/1/3 be scraped [using the API](http://www.ashtadhyayi.com/sutraani/json.php/1/1/1) he provides. It would be useful to write a periodically reusable script to diff our data with the API results as well (TODO: open an issue for this).

I won't take it up now since I want to focus on getting an interface ready first.

**Comment by vvasuki** [comment]
कृतम्।
